### ISSUE TITLE
Feature Request: Possibly `_pr_width` inside `print_result.cmake` could be an Option

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMakeTest#17]
Some of our test names exceed the width of the output in the console. For that we changed the value from `80` to `120` inside `CMakeTest/cmake_test/detail_/utilities/print_result.cmake` for `_pr_width` inside the `_ct_print_result` function.

Maybe that could be an option to change that on `CMakeLists.txt` level.

**Comment by ryanmrichard** [comment]
Sounds good to me. @AutonomicPerfectionist you're much more familiar with the code than me; could we do something like:

```.cmake
include(cmake_test/cmake_test)
ct_set_width(120) # defaults to 80 to make my terminals happy
# Rest of unit test
```
My guess is behind the scenes you'd add a print width to the CMakeTest's state, which would then get honored in the various print functions. I'm advocating for a function because I'm not a huge fan of using global variables to control things, just in case we ever need to have two fixtures running at once or something.
 
@dschiller would that work for you?

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard yes that's possible, with a couple different approaches.

1. We can have each test use a cache variable for the print length that can be adjusted using a cache editor (such as ccmake) or forcefully changed in code through an exposed function.
2. Use a macro or function call to set a variable in the current scope to be propagated down. Works for multiple tests, doesn't touch the cache. This would be equivalent to your above example.
3. We can add an additional option to `ct_add_test()` for print length
4. Dynamically calculate print length based on terminal width, found by executing `tput cols`. This would occur at include time and could have an exposed function to recalculate, but will not be recalculated on every print for performance reasons. Only works on Unix-like systems. Can still be overridden with a cache variable for each test

Let me know which one you think would be best or if there's other solutions you can think of. We can also combine multiple solutions if need be.

**Comment by ryanmrichard** [comment]
I like the idea of combining 2 and 3. That way we could use 2 to set it for the entire file and 3 to set it per test (overriding the file value).
